name: reallystick
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.3
  equatable: ^2.0.5
  http: ^1.2.2
  bloc: ^9.0.0
  meta: ^1.15.0
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  qr_flutter: ^4.1.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  universal_io: ^2.2.2
  http_interceptor: ^2.0.0
  get_it: ^8.0.3
  logger: ^2.4.0
  formz: ^0.8.0
  url_launcher: ^6.3.0
  share_plus: ^10.1.3
  device_info_plus: ^11.2.0
  pointycastle: ^3.9.1
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  bloc_concurrency: ^0.3.0
  web_socket_channel: ^3.0.1
  basic_utils: ^5.7.0
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  emoji_picker_flutter: ^4.3.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  fl_chart: ^0.70.2
  smooth_page_indicator: ^1.2.1
  flutter_markdown: ^0.7.7
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/svg/
    - assets/images/
    - assets/ressources/countries.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600

        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 700

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 900
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
