services:
  db:
    container_name: db
    image: reallystick_db
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - "5432"
    command: -p 5432
    networks:
      - app-network

  backend:
    container_name: backend
    image: reallystick_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
      - redis

  notifications:
    container_name: notifications
    image: reallystick_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.notifications
    env_file:
      - ./backend/.env.notifications.docker
    command:
      [
        "cargo",
        "watch",
        "-q",
        "-c",
        "-w",
        "src/",
        "-x",
        "run --bin notifications",
      ]
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
