services:
  db:
    container_name: db
    image: postgres:16
    build:
      context: ./db
    env_file:
      - ./db/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: api
    image: reallystick_api
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    environment:
      - APP_DATABASE__HOST=db
    env_file:
      - ./backend/.env.docker
    command: "./api/entrypoint.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

  notifications:
    container_name: notifications
    image: reallystick_notifications
    build:
      context: ./backend/notifications
      dockerfile: Dockerfile
    environment:
      - APP_DATABASE__HOST=db
      - APP_APPLICATION__PORT=8001
    env_file:
      - ./backend/.env.docker
    command: "./notifications/entrypoint.sh"
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    depends_on:
      - api
      - db
      - redis

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:


