# Use the official Rust image as the base image
FROM rust:1.81

# Create a new user and switch to that user
RUN useradd -m rustuser
USER rustuser

# Set the working directory inside the container
WORKDIR /app

# Now copy the source code
COPY --chown=rustuser:rustuser . .

# Expose the port the app runs on
EXPOSE 8001
