# Use the official Rust image as the base image
FROM rust:1.80

# Create a new user and switch to that user
RUN useradd -m rustuser
USER rustuser

# Set the working directory inside the container
WORKDIR /app

# Now copy the source code
COPY --chown=rustuser:rustuser . .

# Build the application
RUN cargo build --bin reallystick --release

# Expose the port the app runs on
EXPOSE 8000

# Run the Actix web server
CMD ["./target/release/reallystick"]