// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBChV9ezsc_PAxIMaXriWLOZG8LZxP_7lg',
    appId: '1:32513509893:web:dbf924100cd6f3d789ea6c',
    messagingSenderId: '32513509893',
    projectId: 'reallystick-d807d',
    authDomain: 'reallystick-d807d.firebaseapp.com',
    storageBucket: 'reallystick-d807d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbDaw4swhQzxPsIztU6iZKWLiDA3qQ5vs',
    appId: '1:32513509893:android:d2bcb173b58e4fc489ea6c',
    messagingSenderId: '32513509893',
    projectId: 'reallystick-d807d',
    storageBucket: 'reallystick-d807d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwM1NK-cIIedw3kWLK7ZV5zFsVqVlp2c',
    appId: '1:32513509893:ios:c650b95921eca2e389ea6c',
    messagingSenderId: '32513509893',
    projectId: 'reallystick-d807d',
    storageBucket: 'reallystick-d807d.firebasestorage.app',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpwM1NK-cIIedw3kWLK7ZV5zFsVqVlp2c',
    appId: '1:32513509893:ios:c650b95921eca2e389ea6c',
    messagingSenderId: '32513509893',
    projectId: 'reallystick-d807d',
    storageBucket: 'reallystick-d807d.firebasestorage.app',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBChV9ezsc_PAxIMaXriWLOZG8LZxP_7lg',
    appId: '1:32513509893:web:acc3c1d4c553ec0289ea6c',
    messagingSenderId: '32513509893',
    projectId: 'reallystick-d807d',
    authDomain: 'reallystick-d807d.firebaseapp.com',
    storageBucket: 'reallystick-d807d.firebasestorage.app',
  );
}
